name: Docker_Build
on:
  push:
    branches: [ 1.0.0 ]
  pull_request:
    branches: [ 1.0.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build For food boot
      uses: actions/checkout@v2
    
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository:  food-boot/food_delivery_web_app_backend_springboot/food_delivery_api
        tag_with_ref: true

